name: Pterodactyl Panel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Install Pterodactyl
        run: |
          curl -sSL https://pterodactyl-installer.se | sudo bash
          
      - name: Keep Alive
        run: |
          while true; do
            sleep 300
          done
